eKino/Controllers/FilmoviController.cs
using eKino.Data;
using eKino.Models;
using Microsoft.AspNetCore.Mvc;
using Podaci.EntityModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eKino.Controllers
{
    public class FilmoviController : Controller
    {

        private ApplicationDbContext _db;
        public FilmoviController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Prikaz(int ID, string query)
        {
            List<FilmoviDodajVM> filmovi = null;
            if (ID == 0)
            {
                filmovi = _db.Film
                    .Select(f => new FilmoviDodajVM()
                    {
                        FilmID=f.ID,
                        FilmIme=f.Naziv,
                        SlikaURL=f.SlikaUrl,
                        Godina=f.Godina.ToString(),
                        Reditelj=f.Reditelj,
                        Glumci=f.Glumci,
                        Zanr= f.Zanr,
                        Trajanje=f.TrajanjeMinute.ToString(),
                        TrailerURL=f.TrailerUrl,
                        Info=f.Info
                    })
                    .OrderByDescending(f=>f.Godina)
                    .ThenBy(f=>f.FilmIme)
                    .ToList();
            }

            else
            {
                filmovi = _db.Film
                    .Where(f => f.ID == ID)
                    .Select(f => new FilmoviDodajVM()
                    {
                        FilmID = ID,
                        FilmIme = f.Naziv,
                        SlikaURL = f.SlikaUrl,
                        Godina = f.Godina.ToString(),
                        Reditelj = f.Reditelj,
                        Glumci = f.Glumci,
                        Trajanje = f.TrajanjeMinute.ToString(),
                        TrailerURL=f.TrailerUrl,
                        Info = f.Info
                    })
                    .ToList();
            }
            query = query?.ToLower();
            filmovi = filmovi
                .Where(f => query == "" || query == null || f.FilmIme.ToLower().Contains(query)
                || f.Godina.ToLower().Contains(query) || 
                f.Glumci.ToLower().Contains(query) || f.Reditelj.ToLower().Contains(query))
                .ToList();

            FilmoviPrikazVM model = new FilmoviPrikazVM()
            {
                ID = ID,
                Filmovi = filmovi
            };
            return PartialView(model);
        }
        public IActionResult Dodaj(int ID)
        {
            FilmoviDodajVM model = ID == 0 ? new FilmoviDodajVM() :
                _db.Film
                .Where(f=>f.ID==ID)
                .Select(f => new FilmoviDodajVM()
                { 
                    FilmID=ID,
                    FilmIme=f.Naziv,
                    Godina=f.Godina.ToString(),
                    Zanr=f.Zanr,
                    Reditelj=f.Reditelj,
                    Glumci=f.Glumci,
                    Trajanje=f.TrajanjeMinute.ToString(),
                    SlikaURL=f.SlikaUrl,
                    TrailerURL=f.TrailerUrl,
                    Info=f.Info
                })
                .Single();

            return View(model);
        }
        public IActionResult Snimi(FilmoviDodajVM model)
        {
            Film film=model.FilmID==0? new Film():
                _db.Film.Find(model.FilmID);

            film.Naziv = model.FilmIme;
            film.Godina = int.Parse(model.Godina);
            film.Reditelj = model.Reditelj;
            film.Glumci = model.Glumci;
            film.Zanr = model.Zanr;
            film.TrajanjeMinute = int.Parse(model.Trajanje);
            film.SlikaUrl = model.SlikaURL;
            film.TrailerUrl = model.TrailerURL;
            film.Info = model.Info;

            if(model.FilmID==0)
            {
                _db.Film.Add(film);
            }

            _db.SaveChanges();
            return Redirect("/Filmovi/Prikaz");
        }
    }
}

eKino/Views/Filmovi/Dodaj.cshtml
@{
    ViewData["Title"] = "Dodaj film";
    Layout = "_LayoutAdmin";
}
@model FilmoviDodajVM
<div class="input-div-container">
    <form id="input-form" asp-action="Snimi" asp-controller="Filmovi">
        <input hidden asp-for="FilmID" />
        <div class="input-slika">
            @if (Model.FilmID == 0)
            {
                <img src="https://gooloc.com/wp-content/uploads/vector/36/rnoquhaqlke.jpg" />
            }
            else
            {
                <img src="@Model.SlikaURL"/>
            }
        </div>
        <div class="input-div">
            <label class="input-label">Ime filma</label>
            <input class="input-polje" type="text" placeholder="Ime filma" asp-for="FilmIme" autocomplete="off" />
        </div>
        <div class="input-div">
            <label class="input-label">Slika (URL)</label>
            <input type="text" class="input-polje" id="input-film-slika" placeholder="Slika (URL)" asp-for="SlikaURL" onchange="prikaziSliku()" autocomplete="off" />
        </div>
        <div class="input-div">
            <label class="input-label">Godina</label>
            <input type="text" class="input-polje" placeholder="Godina" asp-for="Godina" autocomplete="off" />
        </div>
        <div class="input-div">
            <label class="input-label">Žanr</label>
            <input type="text" class="input-polje" placeholder="Žanr" asp-for="Zanr" />
        </div>
        <div class="input-div">
            <label class="input-label">Reditelj</label>
            <input type="text" class="input-polje" placeholder="Reditelj" asp-for="Reditelj" autocomplete="off" />
        </div>
        <div class="input-div">
            <label class="input-label">Glumci</label>
            <input type="text" class="input-polje" placeholder="Glumci" asp-for="Glumci" autocomplete="off" />
        </div>
        <div class="input-div">
            <label class="input-label">Trajanje (minute)</label>
            <input type="text" class="input-polje" placeholder="Trajanje" asp-for="Trajanje" autocomplete="off" />
        </div>
        <div class="input-div">
            <label class="input-label">Trailer (URL)</label>
            <input type="text" class="input-polje" placeholder="Trailer (URL)" asp-for="TrailerURL" autocomplete="off" />
        </div>
        <div class="input-div">
            <label class="input-label">Info</label>
            <textarea cols="30" rows="5" asp-for="Info" class="input-textbox"></textarea>
        </div>
        <div class="input-div">
            @if (Model.FilmID == 0)
            {
                <input class="input-submit" type="submit" value="Dodaj" />
            }
            else
            {
                <input class="input-submit" type="submit" value="Sačuvaj promjene" />
            }
        </div>
    </form>
</div>

eKino/Views/Filmovi/Prikaz.cshtml
@{
    ViewData["Title"] = "Svi filmovi";
    //Layout = "_LayoutAdmin";
    @using Microsoft.AspNetCore.Authorization;
    @using Microsoft.AspNetCore.Identity;
    @using Podaci.EntityModels;
}
@inject SignInManager<Korisnik> SignInManager
@inject UserManager<Korisnik> UserManager
@model FilmoviPrikazVM
<div class="filmovi-container">
    @*@if(Model.ID==0)
    {
    <div class="input-div-container">
        <div class="input-div">
            <label class="input-label">Traži</label>
            <input class="input-polje" onkeydown="trazi()" />
        </div>
    </div>
    }*@
    @foreach (var f in Model.Filmovi)
    {
    <div class="film-prikaz">
        <div class="film-naslov">
            <h1>@f.FilmIme</h1>
            <p style="font-size: 28px">(@f.Godina)</p>
        </div>
        <div class="film-podnaslov">
            <p><b>Trajanje:</b> @f.Trajanje min</p>
            <p><b>Žanr:</b> @f.Zanr</p>
        </div>
        <div class="film-prikaz-gore">
            <div><img src="@f.SlikaURL" /></div>
            <div class="film-info">
                <div class="film-info-div"><p>@f.Info</p></div>
                <div>
                    <p><b>Reditelj:</b> @f.Reditelj</p>
                    <p><b>Glumci:</b> @f.Glumci</p>
                </div>
            </div>

        </div>
        <div class="film-prikaz-dolje">

            <div>@Html.Raw(f.TrailerURL)</div>
        </div>
        @if (SignInManager.IsSignedIn(User))
        {
            @if ((UserManager.GetUserAsync(User).Result.IsAdmin || UserManager.GetUserAsync(User).Result.IsModerator))
            {
                <div class="film-prikaz-dugmad">
                    <a href="/Filmovi/Dodaj?ID=@f.FilmID" class="film-prikaz-btn">Uredi</a>
                    <a href="/Filmovi/Obrisi?ID=@f.FilmID" class="film-prikaz-btn delete-btn">Obriši</a>
                </div>
            }
        }


    </div>
    }

</div>