eKino/Controllers/ProjekcijeController.cs
using eKino.Data;
using eKino.Hubs;
using eKino.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using Podaci.EntityModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eKino.Helper_Metode;

namespace eKino.Controllers
{
    public class ProjekcijeController : Controller
    {
        private readonly UserManager<Korisnik> _userManager;
        private readonly SignInManager<Korisnik> _signInManager;
        private ApplicationDbContext _db;
        private IHubContext<NotifikacijaHub> _hubContext;
        public ProjekcijeController(ApplicationDbContext db, UserManager<Korisnik> userManager, 
            SignInManager<Korisnik> signInManager, IHubContext<NotifikacijaHub>  hubContext)
        {
            _db = db;
            _userManager = userManager;
            _signInManager = signInManager;
            _hubContext = hubContext;
        }
        public IActionResult Dodaj(int ID)
        {
            List<SelectListItem> filmovi = _db.Film
                .Select(f => new SelectListItem()
                {
                    Text = f.Naziv,
                    Value = f.ID.ToString()
                })
                .OrderBy(f => f.Text)
                .ToList();

            List<ProjekcijeDodajVM.Filter> sale = _db.Sala
                .Select(s => new ProjekcijeDodajVM.Filter()
                {
                    Ime = s.Oznaka,
                    SalaID = s.ID,
                    Selected = false                  
                })
                .ToList();

            List<string> slike = _db.Film
                .Select(f => f.SlikaUrl)
                .ToList();

            ProjekcijeDodajVM model = new ProjekcijeDodajVM()
            {
                Filmovi = filmovi,
                Sale = sale,
                ProjekcijaId = ID,
                DatumOd = DateTime.Today,
                DatumDo=DateTime.Today,
                Slike=slike
            };
            
            return View(model);
        }
        public IActionResult Prikaz()
        {

            List<ProjekcijePrikazVM.Row> projekcije = _db.Projekcija
                .Select(p => new ProjekcijePrikazVM.Row()
                {
                    ID=p.ID,
                    FilmID=p.FilmID,
                    Film=p.Film.Naziv,
                    Datum=p.Datum,
                    Vrijeme=p.Datum.ToString("H:mm"),
                    Sala=p.Sala.Oznaka,
                    Cijena=p.Cijena.ToString()+" KM",
                    SlikaUrl=p.Film.SlikaUrl,
                    Covid19=p.Covid19 ? "DA" : "NE",
                    Trajanje=p.Film.TrajanjeMinute.ToString()
                })
                .OrderByDescending(p=>p.Datum)
                .ToList();

            ProjekcijePrikazVM model = new ProjekcijePrikazVM()
            {
                Projekcije=projekcije
            };
            return View(model);
        }
        public IActionResult Uredi(int ID)
        {
            List<SelectListItem> sale = _db.Sala
                .Select(s => new SelectListItem()
                {
                    Text = "Sala "+s.Oznaka,
                    Value= s.ID.ToString()
                })
                .ToList();

            Projekcija p = _db.Projekcija
                .Find(ID);
            p.Film = _db.Film.Find(p.FilmID);

            ProjekcijeUrediVM model = new ProjekcijeUrediVM()
            {
                ProjekcijaID = ID,
                FilmIme = p.Film.Naziv,
                SlikaUrl = p.Film.SlikaUrl,
                Datum = p.Datum,
                Vrijeme = p.Datum,
                Covid19 = p.Covid19,
                Cijena = p.Cijena,
                SalaID=p.SalaID,
                Sale=sale
            };
            return View(model);
        }
        public IActionResult Snimi(ProjekcijeDodajVM model)
        {
            if (model.DatumOd > model.DatumDo)
                model.DatumDo = model.DatumOd;

            if (!ModelState.IsValid)
            {
                _hubContext.Clients.User(_userManager
                    .GetUserAsync(User).Result.Id)
                    .SendAsync("prijemNotifikacije",
               _userManager
               .GetUserAsync(User).Result.UserName,
               " je fulio unos ");
                return Redirect("/Projekcije/Dodaj");
            }

            int BrojDana= int.Parse(model.MetodaZakazivanja);
            for (DateTime d = model.DatumOd; d.Date <= model.DatumDo; d = d.Date.AddDays(BrojDana))
            {
                DateTime datum = HelperMetode.SpojiDatumIVrijeme(d, model.Vrijeme);

                //DateTime datumStari = d;
                //DateTime v = model.Vrijeme;
                //DateTime datum = new DateTime(datumStari.Year, datumStari.Month, datumStari.Day, v.Hour, v.Minute, 0);

                foreach (var s in model.Sale)
                {
                    if (s.Selected)
                    {
                        Projekcija projekcija = new Projekcija()
                        {
                            FilmID = model.FilmId,
                            Datum = datum,
                            Covid19 = model.Covid19,
                            Cijena = 5,
                            SalaID=s.SalaID
                        };
                        _db.Projekcija.Add(projekcija);
                    }
                }
            }
            _db.SaveChanges();

            //Film film = _db.Film.Find(model.FilmID);
            //string poruka = "Dodana projekcija!";
            //_hubContext.Clients.All.SendAsync("prijemNotifikacije", poruka);

            return View();
        }
        public IActionResult SnimiPromjene(ProjekcijeUrediVM model)
        {
            Projekcija p = _db.Projekcija.Find(model.ProjekcijaID);

            p.Datum = HelperMetode.SpojiDatumIVrijeme(model.Datum, model.Vrijeme);
            p.Cijena = model.Cijena;
            p.Covid19 = model.Covid19;
            p.SalaID = model.SalaID;

            _db.SaveChanges();

            return Redirect("/Projekcije/Prikaz");
        }
        public IActionResult Obrisi (int ID)
        {
            Projekcija projekcija = _db.Projekcija.Find(ID);
            _db.Remove(projekcija);
            _db.SaveChanges();

            Film film = _db.Film.Find(projekcija.FilmID);
            string poruka = $"Otkazana projekcija filma {film.Naziv} dana {projekcija.Datum.ToString("d.M.yyyy")}. u {projekcija.Datum.ToString("HH:mm")}!";
            _hubContext.Clients.All.SendAsync("prijemNotifikacije", poruka);

            return Redirect("/Projekcije/Prikaz");
        }
    }
}

eKino/Views/Projekcije/Dodaj.cshtml
@{
    ViewData["Title"] = "Dodaj projekcije";
    Layout = "_LayoutAdmin";
}
@model ProjekcijeDodajVM

<form asp-action="Snimi" asp-controller="Projekcije">
    <div id="zakazivanje-container-slika">
        <img src="https://gooloc.com/wp-content/uploads/vector/36/rnoquhaqlke.jpg" />
        <br />
        <h2></h2>
    </div>
    <div id="zakazivanje-container-opcije">
        <div>
            <div class="zakazivanje-komponenta">
                <label>Film</label>
                <br />
                <select class="film-select"
                        asp-for="FilmId"
                        asp-items="Model.Filmovi"
                        onchange="prikaziNazivFilma()">
                    <option selected disabled hidden>Odaberi film</option>
                </select>
                <span asp-validation-for="Filmovi" class="text-danger"></span>
            </div>
            <br />
            <div class="zakazivanje-komponenta">
                <label>Vrijeme</label> <br /><input type="time" asp-for="Vrijeme"/>
                <span asp-validation-for="Vrijeme" class="text-danger"></span>
            </div>
            <div class="zakazivanje-komponenta">
                @for (int i = 0; i < Model.Sale.Count; i++)
                {
                    <input type="checkbox" asp-for="@Model.Sale[i].Selected" />
                    <label asp-for="@Model.Sale[i].Selected">Sala @Model.Sale[i].Ime</label>
                    <input type="hidden" asp-for="@Model.Sale[i].SalaID" />
                    <br />
                }
            </div>
            <div class="zakazivanje-komponenta" style="margin-top: 60px">
                <input type="checkbox" asp-for="Covid19" /> COVID-19 mjere
            </div>
        </div>
        <div>
            <div class="zakazivanje-komponenta">
                <input type="radio"
                       value="1"
                       asp-for="MetodaZakazivanja"
                       checked
                       onclick="omoguciKrajnjiDatum()" />
                Zakaži svaki dan<br />
                <input type="radio"
                       value="7"
                       asp-for="MetodaZakazivanja"
                       onclick="omoguciKrajnjiDatum()" />
                Zakaži svakih 7 dana<br />
                <input id="radio-za-danas"
                       type="radio"
                       asp-for="MetodaZakazivanja"
                       value="1"
                       onclick="omoguciKrajnjiDatum()" />
                Zakaži samo jedan dan
            </div>
            <div class="zakazivanje-komponenta">
                <label id="zakazivanje-datum-od">Od</label>
                <br />
                <input id="datumOdabir" type="date" asp-for="DatumOd" onchange="provjeriDatumDo()"/>
            </div>
            <div class="zakazivanje-komponenta" id="krajnji-datum-div">
                <label>Do</label>
                <br />
                <input id="krajnji-datum" type="date" asp-for="DatumDo" min="@DateTime.Now.Date.ToString("yyyy-mm-dd")"/>
            </div>
            <div class="zakazivanje-komponenta" style="margin-top: 70px">
                <button type="submit" id="film-zakazi-btn">Zakaži</button>
            </div>
        </div>
    </div>
</form>

eKino/Views/Projekcije/Prikaz.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Uredi projekcije";
    Layout = "_LayoutAdmin";
}
@model ProjekcijePrikazVM
<div class="pregled-ponude">
    @foreach (var f in Model.Projekcije)
    {
        <div class="film-ponuda">
            <div class="film-ponuda-desno">
                <div class="film-ponuda-slika">
                    <img src=@f.SlikaUrl />
                </div>
                <div class="film-ponuda-podaci">
                    <div>
                        <h2>@f.Film</h2>
                        <p>@f.Cijena</p>
                        <p>Trajanje: @f.Trajanje min</p>
                    </div>
                    <div class="film-ponuda-opsirnije">
                        <h3>Covid19 mjere: @f.Covid19 </h3>
                    </div>
                </div>
            </div>
            <div class="film-ponuda-lijevo">
                <div class="film-ponuda-termini">
                    <h3>Sala @f.Sala</h3>
                    <p>Datum: @f.Datum.ToString("d.M.yyyy")</p>
                    <p>Termin: @f.Vrijeme</p>
                </div>
            </div>
            <div class="film-ponuda-rezervisi">
                <a href="/Projekcije/Uredi?ID=@f.ID" style="right: 100px">Uredi</a>
                <a href="/Projekcije/Obrisi?ID=@f.ID">Obriši</a>
            </div>
        </div>
    }
</div>
       

eKino/Views/Projekcije/Snimi.cshtml
@*

*@
@{
    Layout = "_LayoutAdmin";
}

<h3>Projekcije uspiješno dodane!</h3>

eKino/Views/Projekcije/Uredi.cshtml
@{
    ViewData["Title"] = "Uredi projekciju";
 Layout = "_LayoutAdmin";
}
@model ProjekcijeUrediVM

<form asp-action="SnimiPromjene" asp-controller="Projekcije">
    <div id="zakazivanje-container-slika">
        <img src="@Model.SlikaUrl" />
        <br />
        <h2>@Model.FilmIme</h2>
    </div>
    <div id="zakazivanje-container-opcije">
        <div>
            <div class="zakazivanje-komponenta">
                <label>Film</label>
                <br />

                <input value="@Model.FilmIme" disabled />
                <input hidden asp-for="ProjekcijaID"/>
            </div>
            <br />
            <div class="zakazivanje-komponenta">
                <label>Vrijeme</label> <br /><input type="time" asp-for="Vrijeme" />
                <span asp-validation-for="Vrijeme" class="text-danger"></span>
            </div>
            <div class="zakazivanje-komponenta">
                <select asp-for="SalaID" asp-items="Model.Sale">

                </select>
            </div>
            <div class="zakazivanje-komponenta" style="margin-top: 60px">
                <input type="checkbox" asp-for="Covid19" /> COVID-19 mjere
            </div>
        </div>

        <div class="zakazivanje-komponenta">
            <label id="zakazivanje-datum-od">Datum</label>
            <br />
            <input id="datumOdabir" type="date" asp-for="Datum" />
            
            <br/>
            <label>Cijena</label>
            <br />
            <input type="text" asp-for="Cijena" />
            
            <div class="zakazivanje-komponenta" style="margin-top: 70px">
                <button type="submit" id="film-zakazi-btn">Sačuvaj promjene</button>
            </div>
        </div>

       
    </div>
</form>