eKino/Controllers/VijestiController.cs
using eKino.Data;
using eKino.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Podaci.EntityModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eKino.Controllers
{
    public class VijestiController : Controller
    {
        private readonly UserManager<Korisnik> _userManager;
        private readonly SignInManager<Korisnik> _signInManager;
        private ApplicationDbContext _db;

        public VijestiController(ApplicationDbContext db, UserManager<Korisnik> userManager,
            SignInManager<Korisnik> signInManager)
        {
            _db = db;
            _userManager = userManager;
            _signInManager = signInManager;
        }
        public IActionResult Dodaj(int ID)
        {
            VijestiDodajVM model = ID == 0 ? new VijestiDodajVM() :
                _db.Vijest
                .Select(v => new VijestiDodajVM()
                {
                    ID=v.ID,
                    Naslov=v.Naslov,
                    Sadrzaj=v.Sadrzaj,
                    SlikaUrl=v.SlikaUrl
                }).ToList()
                .Find(v=>v.ID==ID);

            return View(model);
        }
        public IActionResult Prikaz()
        {
            List<VijestiPrikazVM.Row> vijesti = _db.Vijest
                .Select(v => new VijestiPrikazVM.Row()
                {
                    ID = v.ID,
                    Naslov = v.Naslov,
                    Sadrzaj = v.Sadrzaj,
                    Datum = v.Datum,
                    SlikaUrl = v.SlikaUrl,
                    Korisnik = v.Korisnik.UserName
                })
                .OrderByDescending(v => v.Datum)
                .ToList();

            VijestiPrikazVM model = new VijestiPrikazVM()
            {
                Vijesti = vijesti
            };
            return View(model);
        }
        public IActionResult Snimi(VijestiDodajVM model)
        {
            Vijest vijest = model.ID == 0 ? new Vijest() :
                _db.Vijest.Find(model.ID);

            vijest.Naslov = model.Naslov;
            vijest.Sadrzaj = model.Sadrzaj;
            vijest.SlikaUrl = model.SlikaUrl;
            
            if(model.ID==0)
            {
                vijest.Datum = DateTime.Now;
                vijest.KorisnikID = _userManager.GetUserAsync(User).Result.Id;

                _db.Vijest.Add(vijest);
            }
            _db.SaveChanges();
            return Redirect("/Vijesti/Prikaz");
        }
        public IActionResult Obrisi(int ID)
        {
            Vijest vijest = _db.Vijest.Find(ID);
            _db.Vijest.Remove(vijest);
            _db.SaveChanges();
            return Redirect("/Vijesti/Prikaz");
        }
    }
}

eKino/Views/Vijesti/Dodaj.cshtml
@{
    ViewData["Title"] = "Dodaj vijest";
    Layout = "_LayoutAdmin";
}
@model VijestiDodajVM
<div class="input-div-container">
    <form id="input-form" asp-action="Snimi" asp-controller="Vijesti">
        <input hidden asp-for="ID" />
        <div class="input-slika">
            @if (Model.ID == 0)
            {
                <img src="https://gooloc.com/wp-content/uploads/vector/36/rnoquhaqlke.jpg" style="width: auto"/>
            }
            else
            {
                <img src="@Model.SlikaUrl" />
            }
        </div>
        <div class="input-div">
            <label class="input-label">Naslov</label>
            <input class="input-polje" type="text" placeholder="Naslov" asp-for="Naslov" autocomplete="off" />
        </div>
        <div class="input-div">
            <label class="input-label">Slika (URL)</label>
            <input type="text" class="input-polje" id="input-film-slika" placeholder="Slika (URL)" asp-for="SlikaUrl" onchange="prikaziSliku()" autocomplete="off" />
        </div>
       
        <div class="input-div">
            <label class="input-label">Sadrzaj</label>
            <textarea cols="50" rows="100" asp-for="Sadrzaj" class="input-textbox" style="width: 100%"></textarea>
        </div>
        <div class="input-div">
            @if (Model.ID == 0)
            {
                <input class="input-submit" type="submit" value="Dodaj" />
            }
            else
            {
                <input class="input-submit" type="submit" value="Sačuvaj promjene" />
            }
        </div>
    </form>
</div>

eKino/Views/Vijesti/Prikaz.cshtml
@{
    Layout = "_LayoutAdmin";
    ViewData["title"] = "Sve vijesti";
}
@model VijestiPrikazVM
    <div class="vijesti-sve-container">
        @foreach (var v in Model.Vijesti)
        {
            <div class="vijest-container">
                <div>
                    <div><h2>@v.Naslov</h2></div>
                    <div><b>Napisao: </b>@v.Korisnik, @v.Datum.ToString("d.M.yyyy"). u @v.Datum.ToString("HH:mm") sati</div>
                </div>
                <div>
                    <img src="@v.SlikaUrl" style="height: 300px" />
                </div>
                <div>
                    <p>@v.Sadrzaj</p>
                </div>
                <div>
                    <a href="/Vijesti/Dodaj?ID=@v.ID" class="film-prikaz-btn">Uredi</a>
                    <a href="/Vijesti/Obrisi?ID=@v.ID" class="film-prikaz-btn delete-btn">Obriši</a>
                </div>
            </div>
        }
    </div>